config/routes.rb
Rails.application.routes.draw do

	root 'servers#index'

	resources :servers

	get 'server' => 'servers#show'
	post 'server' => 'servers#show'
	get 'server/:name' => 'servers#show'
	post 'server/:name' => 'servers#show'

	get 'update' => 'servers#update_ip'
	post 'update' => 'servers#update_ip'

end

app/models/server.rb
class Server < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true
    validates :admin_password, presence: true

    has_many :updates

    def last_update
        updates.sort_by{|u| u.created_at}.last || nil
    end
end

app/models/update.rb
class Update < ActiveRecord::Base
	include ActionView::Helpers::TextHelper

	belongs_to :server

	validates :ip_address, format: {
			with: /(?:\d{1,3}\.){3}\d{1,3}/,
			message: 'not a valid IP address' }

	def duration
		mins = ((updated_at - created_at)/60).round
		hours = mins / 60
		days = hours / 24

		if days > 0
			"#{pluralize days, 'day'} and #{pluralize (hours % 24), 'hour'}"
		elsif hours > 0
			"#{pluralize hours, 'hour'} and #{pluralize (mins % 60), 'minute'} minutes"
		elsif mins > 0
			pluralize mins, 'minute'
		else
			'1 minute'
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

	# /
	def home
	end

	# /servers
	def index
		@servers = Server.order(:name)
	end

	# /servers/1
	# /server/name
	# /server/name.json
	def show
		unless set_server
			respond_to do |format|
				format.html {redirect_to root_url, :flash => {:error => 'Server not found' } }
				format.json {render json: 'Server not found', status: :not_found}
			end
			return
		end
		unless require_password
			respond_to do |format|
				format.html {redirect_to root_url, :flash => {:error => 'Incorrect server/password combination'} }
				format.json {render json: 'Wrong password', status: :not_authorized}
			end
			return
		end
		respond_to do |format|
			format.html {render}
			format.json {
				res = {
					name: @server.name,
					description: @server.description,
				}
				if u = @server.last_update
					res[:ip_address] = u.ip_address
					res[:duration] = u.duration
				else
					res[:ip_address] = ''
					res[:duration] = ''
				end
				render json: res
			}
		end
	end

	# /update.json
	def update_ip
		unless set_server
			render json: {error: 'Server not found'}, status: :not_found
			return
		end
		unless require_admin_password
			render json: {error: 'Incorrect server/password combination'}, status: :forbidden
			return
		end

		ip = request.remote_ip
		ip = '127.0.0.1' if ip == '::1' #Don't allow IPv6 formatted localhost

		if last_update = @server.last_update
			if last_update.ip_address == ip
				# Previous IP is the same
				last_update.touch
				u = last_update
			else
				# Previous IP doesn't match
				u = @server.updates.build(:ip_address => ip)
			end
		else
			# First IP update
			u = @server.updates.build(:ip_address => ip)
		end

		if u.save
			render json: 'IP Address updated'
		else
			render json: {error: 'Update could not be saved'}, status: :bad_request
		end
		return
	end

	# GET /servers/new
	def new
		@server = Server.new
	end

	# POST /servers
	def create
		@server = Server.new(server_params)

		if @server.save
			redirect_to "/server/#{@server.name}?password=#{@server.password}", notice: 'Server was successfully created.'
		else
			render :new
		end
	end

	# GET /servers/1/edit
	def edit
		unless set_server
			redirect_to :index, :flash => {:error => 'Server not found.'}
		end
		@authorized = require_admin_password
	end

	# PATCH/PUT /servers/1
	def update
		unless set_server
			redirect_to action: :index, :flash => {:error => 'Server not found.'}
			return
		end
		unless require_admin_password
			redirect_to action: :index, :flash => {:error => 'Password required.'}
			return
		end
		if @server.update(server_params)
			redirect_to "/server/#{@server.name}?password=#{@server.password}", notice: 'Server was successfully updated.'
			return
		else
			render :edit
		end
	end

	# DELETE /servers/1
	def destroy
		unless set_server
			redirect_to action: :index, :flash => {:error => 'Server not found.'}
			return
		end
		unless require_admin_password
			render
			return
		end
		@server.destroy
		redirect_to servers_url, notice: 'Server was successfully destroyed.'
	end

	private
		def set_server
			@server = Server.find_by_id(params[:id]) if params[:id] and !params[:id].blank?
			@server = Server.find_by_name(params[:name]) if @server.nil? and params[:name] and !params[:name].blank?
			return !@server.nil?
		end

		# Require password = server.password
		def require_password
			return (params[:password] and params[:password] == @server.password)
		end

		# Require password = server.admin_password
		def require_admin_password
			return (params[:password] and params[:password] == @server.admin_password)
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def server_params
			params.require(:server).permit(:name, :description, :password, :admin_password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="span8 offset2">
	<h1>
	<%= link_to image_tag('otter_meme.jpg'), root_path %>
	<%= @page_title %>
	</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title or 'Dynipo' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<!-- Header -->
	<div class="row-fluid header">
		<%= render :partial => 'layouts/header' %>
	</div>
	<!-- Flash -->
	<div class="row-fluid">
		<div class="span6 offset3">
			<%= bootstrap_flash %>
		</div>
	</div>
	<!-- Content -->
	<div class="row-fluid">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/servers/destroy.html.erb
<% @page_title = 'Deleting server' -%>

<div class="span6 offset3">
	<div class="well">

	<%= form_tag request.original_url, method: :delete, class: 'form-horizontal' do |f| -%>
		<div class="control-group">
			<%= label_tag :name, 'Server Name', class: 'control-label' %>
			<div class="controls">
				<%= text_field_tag nil, @server.name, disabled: true, class: 'span12' %>
			</div>
		</div>
		<div class="control-group">
			<%= label_tag :password, 'Admin password', class: 'control-label' %>
			<div class="controls">
				<%= text_field_tag :password, nil, class: 'span12' %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= submit_tag 'Delete', name: nil, class: 'btn btn-primary' %>
				<%= link_to 'Back', "/server/#{@server.name}?password=#{@server.password}" %>
			</div>
		</div>
	<% end -%>

	</div>
</div>

app/views/servers/edit.html.erb
<% @page_title = 'Editing server' -%>

<div class="span6 offset3">
	<div class="well">

<% if !@authorized -%>

	<%= form_tag request.original_url, method: :get, class: 'form-horizontal' do |f| -%>
		<div class="control-group">
			<%= label_tag :name, 'Server Name', class: 'control-label' %>
			<div class="controls">
				<%= text_field_tag nil, @server.name, disabled: true, class: 'span12' %>
			</div>
		</div>
		<div class="control-group">
			<%= label_tag :password, 'Admin password', class: 'control-label' %>
			<div class="controls">
				<%= text_field_tag :password, nil, class: 'span12' %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= submit_tag 'Edit', name: nil, class: 'btn btn-primary' %>
				<%= link_to 'Back', "/server/#{@server.name}?password=#{@server.password}" %>
			</div>
		</div>
	<% end -%>

<% else -%>
	<%# Authorized -%>

		<%= form_for @server, :html => {class: 'form-horizontal'} do |f| %>
			<%= hidden_field_tag :password, @server.admin_password %>
			<% if @server.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

					<ul>
					<% @server.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
					</ul>
				</div>
			<% end %>

			<div class="control-group">
				<%= f.label :name, class: 'control-label' %>
				<div class="controls"><%= f.text_field :name, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :description, class: 'control-label' %>
				<div class="controls"><%= f.text_field :description, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :password, class: 'control-label' %>
				<div class="controls"><%= f.text_field :password, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :admin_password, class: 'control-label' %>
				<div class="controls"><%= f.text_field :admin_password, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<div class="controls">
					<%= f.submit 'Update', class: 'btn btn-primary' %>
					<%= link_to 'Show', "/server/#{@server.name}?password=#{@server.password}" %>
				</div>
			</div>
		<% end %>

<% end -%>

	</div>
</div>

app/views/servers/index.html.erb
<% @page_title = 'Dynamic IP Otter' -%>

<div class="span6 offset1">
	<div class="well">

		<%= form_tag '/server', method: 'get', class: 'form-horizontal' do |f| -%>
			<div class="control-group">
				<%= label_tag :name, 'Server Name', class: 'control-label' %>
				<div class="controls"><%= text_field_tag :name, nil, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= label_tag :password, 'Password', class: 'control-label' %>
				<div class="controls"><%= text_field_tag :password, nil, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<div class="controls"><%= submit_tag 'View', name: nil, class: 'btn btn-primary' %></div>
			</div>
		<% end -%>

	</div>
</div>

<div class="span3 offset1">
	<div class="well">
		<%= link_to 'New Server', new_server_path %>
	</div>
<div>

app/views/servers/new.html.erb
<% @page_title = 'New server' -%>

<div class="span6 offset3">
	<div class="well">

		<%= form_for @server, :html => {class: 'form-horizontal'} do |f| %>
			<% if @server.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

					<ul>
					<% @server.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
					</ul>
				</div>
			<% end %>

			<div class="control-group">
				<%= f.label :name, class: 'control-label' %>
				<div class="controls"><%= f.text_field :name, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :description, class: 'control-label' %>
				<div class="controls"><%= f.text_field :description, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :password, class: 'control-label' %>
				<div class="controls"><%= f.text_field :password, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<%= f.label :admin_password, class: 'control-label' %>
				<div class="controls"><%= f.text_field :admin_password, class: 'span12' %></div>
			</div>
			<div class="control-group">
				<div class="controls">
					<%= f.submit 'Create', class: 'btn btn-primary' %>
					<%= link_to 'Back', root_path %>
				</div>
			</div>
		<% end %>

	</div>
</div>

app/views/servers/show.html.erb
<% @page_title = @server.nil? ? 'Find Server' : "Server - #{@server.name}" -%>

<div class="span6 offset3">
	<div class="well">

		<h2><%= @server.name %></h2>
		<% unless @server.description.nil? or @server.description.blank? -%>
			<blockquote><%= @server.description %></blockquote>
		<% end -%>

		<p>
			<%= link_to 'Edit', edit_server_path(@server) %> |
       <%= link_to 'Destroy', @server, method: :delete %>
		</p>

		<strong>IP Addresses:</strong>
		<% for u in @server.updates.sort_by{|u| u.created_at}.reverse -%>
			<li><strong><%= u.ip_address %></strong> for <%= u.duration %>, last updated <%= u.updated_at %></li>
		<% end -%>

	</div>
</div>